name = "Steamon Client"
author = "Gaspard4i"
version = "0.3.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b7cfdde6ed44716ca6d715be4f9088373ed5ba22ea6dc3b34acb34969597de42"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
