name = "Steamon Client"
author = "Gaspard4i"
version = "2.0.9-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0d995c6a0bdbf6aa9402e0cf98ee6a9db651caf6b311045699176a23f943c20c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.251"

[options]
datapack-folder = "world/datapacks"
