name = "Steamon Client"
author = "Gaspard4i"
version = "0.6.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e907d6f4272c950965ad9dd4f70af9006363d47e799f4d041693833fbc6652db"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
