name = "Steamon Server"
author = "Gaspard4i"
version = "2.0.11-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d10d3172c74f71ad19c0d03145507dcdb02723ae0530c8a4377be9f793cd0e0a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"

[options]
datapack-folder = "world/datapacks"
