name = "Steamon Server"
author = "Gaspard4i"
version = "0.10.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "45f5d55da2cf095ccc0b8b5efaed1c6f92d0d425404535af20d8f22737c68f8b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"

[options]
datapack-folder = "world/datapacks"
